version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    build:
      html:
        - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
